server:
  port: ${SERVER_PORT}

spring:
  application: 
    name: ${SERVER_NAME}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${EUREKA_HOST}
  server:
    renewal-percent-threshold: ${EUREKA_RENEWAL}
